#ifndef FW_CONFIG_H
#define FW_CONFIG_H

#define FW_IS_FULLSCREEN_ENABLED TRUE
#define FW_IS_FULLSCREEN_BORDERLESS_ENABLED FALSE

#define FW_IS_MUSIC_ENABLED TRUE

#define FW_WINDOW_NAME  "MEGA INTRO - SPECTROX"

#define FW_WINDOW_WIDTH  640
#define FW_WINDOW_HEIGHT 400

#define FW_RENDER_WIDTH  320
#define FW_RENDER_HEIGHT 200

#endif
